<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit821f3eac70bf463a44c7f6b2e5113512
{
    public static $files = array (
        'b7e1c4cbafbabee94a69519a450ea263' => __DIR__ . '/..' . '/kucrut/vite-for-wp/vite-for-wp.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib3\\' => 11,
        ),
        'P' => 
        array (
            'ParagonIE\\ConstantTime\\' => 23,
            'Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 38,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib3\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'ParagonIE\\ConstantTime\\' => 
        array (
            0 => __DIR__ . '/..' . '/paragonie/constant_time_encoding/src',
        ),
        'Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 
        array (
            0 => __DIR__ . '/..' . '/pablo-sg-pacheco/wp-namespace-autoloader/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit821f3eac70bf463a44c7f6b2e5113512::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit821f3eac70bf463a44c7f6b2e5113512::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit821f3eac70bf463a44c7f6b2e5113512::$classMap;

        }, null, ClassLoader::class);
    }
}
